// questions.js

const questions = [
  // Add your questions here

  {
    question_text:
      "Which of the following is the best way to declare a variable in JavaScript?",
    question_type: "multiple_choice",
    options: ["int", "let", "float", "for"],
    correct_option: 1,
    correct_explanation:
      "let is correct because the other terms are not variables .",
  },

  {
    question_text: "Who is the dark knight of SoC?",
    question_type: "multiple_choice",
    options: ["Chris Meah", "Anna-Marie Moss", "Faisal Ali", "Olivia Butcher"],
    correct_option: 0,
    correct_explanation: "Clearly demonstrated in his pixel character",
  },

  {
    question_text: "Which option is a good way to give feedback?",
    question_type: "multiple_choice",
    options: [
      "Here’s what you should do.",
      "That didn’t really work.",
      "Here are three things that really worked for me.",
      "You need to improve your communication skills.",
    ],
    correct_option: 2,
    correct_explanation:
      "When giving feedback, remember that it's highly subjective. Also, starting positively can help put feedback receivers in the right frame of mind to strive for excellence.",
  },

  {
    question_text:
      "Which of these is the SoC’s conventional analogy for pair programming?",
    question_type: "multiple_choice",
    options: [
      "Motorbike-Pedal Bike",
      "Clippy-Microsoft Word",
      "Hiker-Racecar",
      "Workman-Tools",
    ],
    correct_option: 2,
    correct_explanation:
      "This analogy reflects the slow, more methodical approach of the Navigator, where the Racecar is the more output-focused mindset of the Driver",
  },

  {
    question_text: "Which is the first stage of the Disney Ideation method?",
    question_type: "multiple_choice",
    options: ["critics room", "dreamer room", "writing plan", "realist room"],
    correct_option: 1,
    correct_explanation:
      "Be as creative as possible without barriers in the dreamer room",
  },

  {
    question_text:
      "Which of the following is a key principle of Agile methodology?",
    question_type: "multiple_choice",
    options: [
      "Strict adherence to initial plans",
      "Delivering working software frequently",
      "Comprehensive documentation over collaboration",
      "Avoiding customer feedback during development",
    ],
    correct_option: 1,
    correct_explanation:
      "Agile workflow focuses on incremental software updates and constant customer communication.",
  },

  {
    question_text:
      "In the Git Hub workflow process, which command comes first?",
    question_type: "multiple_choice",
    options: ["git branch", "git add", "git commit", "git push"],
    correct_option: 1,
    correct_explanation:
      "The git add command is used to stage changes in your working directory for the next commit.",
  },

  {
    question_text:
      "In a Generative Adversarial Network (GAN), what is the role of the discriminator?",
    question_type: "multiple_choice",
    options: [
      "To generate new data similar to the training data.",
      "To differentiate between real and generated data.",
      "To train the generator by providing labels.",
      "To modify the generated data to make it more realistic.",
    ],
    correct_option: 1,
    correct_explanation:
      "The discriminator in a GAN acts like a judge. Its main job is to determine whether the input data is real (from the training set) or fake (generated by the generator). By doing so, it helps the generator improve at creating realistic data.",
  },

  {
    question_text: "Which of these is NOT a stage in computational thinking?",
    question_type: "multiple_choice",
    options: [
      "Understanding the problem",
      "Breaking it down",
      "Looking for patterns",
      "Panicking",
    ],
    correct_option: 3,
    correct_explanation: "Panicking is never helpful!",
  },

  {
    question_text: "What is the role of backpropagation?",
    question_type: "multiple_choice",
    options: [
      "To review your code upon completion to debug any issues",
      "To push your updated branch to Github for review",
      "Replacement of current working version of your code with a previous Git commit.",
      "The reevaluation of neuron weights to allow for the GAN to provide more reliable output.",
    ],
    correct_option: 3,
    correct_explanation:
      "Backpropagation is a machine learning technique essential to the optimization of artificial neural networks.",
  },
];

// Don't worry about this, we're just exporting the questions
module.exports = questions;

// Each question should be an object with the following properties:

//question_text: This is a string that contains the text of the question you want to ask.
//question_type: This should always be the string "multiple_choice" for this task.
//options: This is an array of strings, where each string is a possible answer to the question. You should provide four options.
//correct_option: This is a number that represents the index of the correct answer in the options array. The index is 0-based, meaning the first option is 0, the second is 1, and so on.
//correct_explanation: This is a string that explains why the correct answer is correct. This helps learners understand the reasoning behind the answer.
